import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "@/components/navbar/Navbar";
import NextThemeProviders from "./providers/NextThemeProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
      <body className="bg-background text-foreground">
        <NextThemeProviders>
          <Navbar></Navbar>
        <main>
          {children}
        </main>
        {/* <ToastContainer position="top-center" /> */}
        </NextThemeProviders>
      </body>
    </html>
  );
}
